mod death;
mod destroy;
mod effect;
mod hit;
mod input;
mod log;
mod projectile;
mod shoot;
mod spot;
mod view;
mod wall;

pub use death::system as death;
pub use destroy::system as destroy;
pub use effect::system as effect;
pub use hit::system as hit;
pub use input::system as input;
pub use log::system as log;
pub use projectile::system as projectile;
pub use shoot::system as shoot;
pub use spot::system as spot;
pub use view::system as view;
pub use wall::system as wall;
