mod ai;
mod combat;
mod death;
mod destroy;
mod door;
mod dwim;
mod gateway;
mod god_mode;
mod lock;
mod melee;
mod memorize;
mod r#move;
mod radial_lines;
mod room;
mod shoot;
mod spot;
mod state;
mod switch;
mod view;

pub use ai::behavior as ai;
pub use combat::damage as combat_damage;
pub use combat::hit as combat_hit;
pub use death::behavior as death;
pub use destroy::behavior as destroy;
pub use door::behavior as door;
pub use dwim::close as dwim_close;
pub use dwim::r#move as dwim_move;
pub use dwim::shoot as dwim_shoot;
pub use gateway::behavior as gateway;
pub use god_mode::behavior as god_mode;
pub use lock::close as lock_close;
pub use lock::door as lock_door;
pub use melee::attack as melee_attack;
pub use melee::intent as melee_intent;
pub use memorize::ai as ai_memorize;
pub use memorize::behavior as memorize;
pub use r#move::behavior as r#move;
pub use room::behavior as room;
pub use shoot::dispatch_projectile;
pub use shoot::intent as shoot_intent;
pub use shoot::shoot_projectile;
pub use spot::behavior as spot;
pub use state::behavior as state;
pub use switch::behavior as switch;
pub use view::behavior as view;
pub use view::view_all;

pub use radial_lines::setup as radial_lines;
